# Generated by Django 4.2.2 on 2023-07-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_staff_alternate_mobile_no_alter_staff_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_of_joining',
            field=models.DateField(null=True),
        ),
    ]
