# Generated by Django 4.2.2 on 2023-07-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_staff_date_of_joining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='subject_details',
        ),
    ]
