# Generated by Django 4.2.2 on 2023-07-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_remove_staff_subject_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='class_details',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='subject_details',
            field=models.IntegerField(null=True),
        ),
    ]
