# Generated by Django 4.2.2 on 2023-07-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_alter_students_mothers_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='students',
            name='user',
        ),
    ]
