# Generated by Django 4.2.3 on 2023-07-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_remove_staff_user_remove_students_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
